### ISSUE TITLE
Datamatrix generation max capacity Alphanumerics fail

### ISSUE THREAD

**Issue by guiguivarch** [woo-j/OkapiBarcode#21]
I m using release 0.1

I was evaluating this library and typically in my use case.
I m setting a preferred size for the datamatrix, and generating a random alphaNumeric numbers. Some of them fail. 
DM12x12 (max alpha size is 6) encode value "9HR3Z6" it fails:
        "Data does not fit in selected symbol size"

This data should fit if we encode in C40. I see the library is evaluating the best encoding type, but typical for this case it s unable to encode it. 

For instance encoding 9HR3ZT in a DM12x12 will work

is there any kind of workaround ? to force encoding type?

Note if that can help:
Alphanumerics composed of only  upercase char work
Alphanumerics composed of alternance of upper case and numerics cause this problem.

**Comment by pleuba** [comment]
Hi Guillaume,

The problem comes from the fact that the same data may be represented by different Data
Matrix symbols through the use of different code sets.

This java implementation (and the c++ zint one) try to follow the algorithm of Annexe S (Informative)
"Encoding Data Using the Minimum Symbol Data Characters for ECC 200" of ISO/IEC 16022:2000.

The given algorithm will **usually** produce the shortest codeword stream.

For your specific use cases, it was not producing the shortest result. A solution could be to have an option to bypass the algorithm and specifying the code set (this could speed up the encoding as well).

Philippe

**Comment by woo-j** [comment]
Hi Guillaume,

Thank you for giving Okapi such a thorough test and finding this issue.

I like Philippe's idea of setting an option for this, and it would also be useful for debugging if we could force a particular encoding method. I would be reluctant, however, to add even more user options to the GUI. Perhaps a method for reading user preferences from file may be more appropriate for these "advanced" requirements?

Robin.

**Comment by woo-j** [comment]
On second look, however, maybe this is a bug after all...

I have just updated the code to more correctly follow Annex P from ISO 16022:2006 and your test data 9HR3Z6 now encodes in a 12x12 matrix. Could you run your tests again, and let me know if this solves the problem?

Robin.

**Comment by pleuba** [comment]
Your fix aligns more closely to the given algorithm, but still not strictly, for example step R, specify that we need to do some checks after 4 data characters, or step K specify some others rules when we are at the end of data.

The algorithm should only be used for general usages, but I continue to think that an option to force the characters set could be very useful for certain use cases, e.g. if we know to encode only alphanumeric characters, no need to perform all these time intensive calculations. No need to provide this option in GUI.

**Comment by woo-j** [comment]
Hi Philippe,

I have updated the code again - it should now align exactly with Annex J including steps R and K. Please let me know if you see any further omissions.

Robin.

**Comment by pleuba** [comment]
Hi Robin,

I saw two things:
- At line 1251: "if (ascii_count < best_count) {" should be "<="
- Not sure about j_r_6_2_1 when they mention "in the yet to be processed data", does it mean characters before or after current position ?

Thanks for the work.

Philippe Leuba

**Comment by woo-j** [comment]
Hi Philippe,

I have had added your correction, and had another attempt at this function. You are right that it was looking at the wrong data, but I'm still not sure what the standard is asking for. In particular what does it mean by "**first** occurs" and does "before" mean immediately before?

I have checked the ISO corrigenda, but there is nothing for Annex P.

Robin

**Comment by guiguivarch** [comment]
Sorry for the super late reply,

I have run some test against your release 0.1.2.

but still get this kind of errors:
cannot encode O8T8G72IDI format:DM14x14

It can fail with the max numeric capacity as well.

**Comment by gredler** [comment]
This appears to be fixed with the latest code update. Please open a new bug if you run into any more capacity edge cases. Thanks!
